### ISSUE TITLE
L5.4 error

### ISSUE THREAD

**Issue by Palvaneh** [KaveNegar/kavenegar-laravel#1]
`[Symfony\Component\Debug\Exception\FatalThrowableError]`
`Call to undefined method Illuminate\Foundation\Application::share()`

**Comment by bgsrb** [comment]
thank you
fixed

**Comment by Palvaneh** [comment]
thanks so much
please update version to 1.0.1
`composer require kavenegar/laravel`
downloads v1.0.0 :(
