### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by saber13812002** [kavenegar/kavenegar-laravel#12]
thanks for this library

but i need more samples about this line:

 Kavenegar::Send($sender,$receptor,$message)

if we want to call another rest api and another method we need to know about optional and required fields.

how to send templatename in verify method

if possible give us more samples

or add a sample for each method

thanks in advanced

**Comment by mohsenk** [comment]
Hi Saber,
For using lookup API you can use this code snippet : 

https://github.com/kavenegar/kavenegar-examples-php/blob/master/src/VerifyLookup.php

Thanks.
