### ISSUE TITLE
Laravel 6.0 not supported 

### ISSUE THREAD

**Issue by mohammad-salehnia** [kavenegar/kavenegar-laravel#16]
![Screenshot (103)](https://user-images.githubusercontent.com/12606608/64862452-c9500f00-d647-11e9-8c82-b9c05b1a00c7.png)

**Comment by AmirMehrabi** [comment]
I took care of it and sent a merge request to the guys over at Kavenegar, which they haven't checked yet. For the time being, take a look at my forked repo:
https://github.com/AmirMehrabi/kavenegar-laravel

**Comment by vahidalvandi** [comment]
do it support queue ?
