### ISSUE TITLE
Laravel 8 is not supported

### ISSUE THREAD

**Issue by mohsenMJ** [kavenegar/kavenegar-laravel#30]
I can't install this package with Laravel 8, please add support for Laravel 8 too

**Comment by sxshateri** [comment]
same here. it is not supported on Laravel 8. 

```
does not comply with psr-4 autoloading standard
and
Your version of Laravel is not supported
```

errors showing up.

**Comment by hosseinRezaei188** [comment]
laravel pakage updated to 8 version
