### ISSUE TITLE
Laravel 8.* is not Supported

### ISSUE THREAD

**Issue by LegenD1995** [kavenegar/kavenegar-laravel#31]
Hey, 

Please fix these issues for latest version of Laravel as soon as possible:
`php
 Class Kavenegar\Laravel\Notification\KavenegarBaseNotification & Kavenegar\Laravel\Channel\KavenegarChannel does not comply with psr-4 autoloading standard, It will not autoload anymore in Composer v2.0.
`

Appreciatively

**Comment by h-o-sein** [comment]
https://github.com/h-o-sein/kavenegar-laravel

**Comment by mhyeganeh** [comment]
+1

![kavenegar](https://user-images.githubusercontent.com/32367934/99195360-6ce00680-279a-11eb-846a-d8c7ab78677f.jpg)
