### ISSUE TITLE
Driver [kavenegar] not supported.

### ISSUE THREAD

**Issue by Rasool-deldar** [kavenegar/kavenegar-laravel#39]
I am using the latest version (1.3.2) but there is still the same error, please fix this problem faster.

Laravel v8.43.0 (PHP v8.0.3)

**Comment by hosseinRezaei188** [comment]
We are sorry for the delay in replying.
in latest release ([v1.3.4](https://github.com/kavenegar/kavenegar-laravel/releases/tag/V1.3.4)) this issue fixes.
